import { useState } from "react";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { ExternalLink, MapPin, FileText, Copy, Download, CheckCheck, AlertTriangle } from "lucide-react";
import type { SupplierResponse } from "@shared/routes";

const MAX_SCORE = 8;

interface SuppliersTableProps {
  suppliers: SupplierResponse[];
  jobSpec?: string;
  quantity?: number | null;
  certifications?: string | null;
}

function buildRfqDraft(supplier: SupplierResponse, jobSpec: string, quantity?: number | null, certifications?: string | null): string {
  const today = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  return `REQUEST FOR QUOTATION (RFQ)
${"=".repeat(60)}

Date: ${today}
Reference: RFQ-SS-${supplier.id?.toString().padStart(4, "0") ?? "0001"}

FROM (Buyer):
  [Your Company Name]
  [Your Name, Title]
  [Email Address]
  [Phone Number]

TO (Supplier):
  ${supplier.name}
  ${supplier.location ?? "Location not specified"}
  ${supplier.url ? `Website: ${supplier.url}` : ""}

${"─".repeat(60)}
PRODUCT SPECIFICATION
${"─".repeat(60)}

${jobSpec}

${"─".repeat(60)}
REQUIREMENTS
${"─".repeat(60)}

  Order Quantity:       ${quantity ? quantity.toLocaleString() + " units" : "To be discussed"}
  Required Certs:       ${certifications || "None specified"}
  Supplier Certs:       ${supplier.certifications || "Not listed"}
  Supplier MOQ:         ${supplier.moq ? supplier.moq.toLocaleString() + " units" : "To be confirmed"}
  Supplier Location:    ${supplier.location || "To be confirmed"}

${"─".repeat(60)}
REQUESTED INFORMATION
${"─".repeat(60)}

Please provide a quotation including the following:

  1. Unit price (at our target quantity)
  2. Tooling / setup costs (if applicable)
  3. Lead time (from PO to delivery)
  4. Payment terms
  5. Minimum order quantity (MOQ) confirmation
  6. Sample availability and cost
  7. Quality certifications held
  8. Delivery terms (Incoterms)

${"─".repeat(60)}
DEADLINE & CONTACT
${"─".repeat(60)}

Please respond within 5 business days.

[Your Name]
[Your Email]
[Your Phone]

${"=".repeat(60)}
Generated by SupplyScout — supplyscout.app
`;
}

export function SuppliersTable({ suppliers, jobSpec = "", quantity, certifications }: SuppliersTableProps) {
  const [rfqSupplier, setRfqSupplier] = useState<SupplierResponse | null>(null);
  const [copied, setCopied] = useState(false);

  const rfqText = rfqSupplier ? buildRfqDraft(rfqSupplier, jobSpec, quantity, certifications) : "";

  const handleCopy = () => {
    navigator.clipboard.writeText(rfqText).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const handleDownload = () => {
    if (!rfqSupplier) return;
    const blob = new Blob([rfqText], { type: "text/plain;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `RFQ-${rfqSupplier.name.replace(/\s+/g, "-")}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (suppliers.length === 0) {
    return (
      <div className="p-12 text-center text-slate-500 bg-white rounded-xl border border-slate-200 shadow-sm">
        No suppliers found for this job.
      </div>
    );
  }

  return (
    <>
      <div className="bg-white rounded-xl shadow-sm border border-slate-200/80 overflow-hidden">
        <Table>
          <TableHeader className="bg-slate-50/80">
            <TableRow>
              <TableHead className="font-semibold">Supplier</TableHead>
              <TableHead className="font-semibold">Location</TableHead>
              <TableHead className="font-semibold">Certifications</TableHead>
              <TableHead className="font-semibold text-right">MOQ</TableHead>
              <TableHead className="font-semibold">Match Score</TableHead>
              <TableHead className="font-semibold text-right">Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {suppliers.map((s) => {
              const isVerified = (s.confidenceScore ?? 0) >= 90;
              const scorePercent = Math.round(((s.score ?? 0) / MAX_SCORE) * 100);

              return (
                <TableRow key={s.id} className="hover:bg-slate-50/50 transition-colors">
                  <TableCell className="font-medium text-slate-900">
                    <div className="flex flex-col gap-0.5">
                      {isVerified && s.url ? (
                        <a
                          href={s.url}
                          target="_blank"
                          rel="noreferrer"
                          className="flex items-center gap-1.5 text-primary hover:text-blue-700 hover:underline transition-colors"
                          data-testid={`link-supplier-${s.id}`}
                        >
                          {s.name} <ExternalLink className="w-3.5 h-3.5 shrink-0" />
                        </a>
                      ) : (
                        <span data-testid={`text-supplier-${s.id}`}>{s.name}</span>
                      )}
                      {!isVerified && (
                        <span className="flex items-center gap-1 text-[11px] text-amber-600 font-medium">
                          <AlertTriangle className="w-3 h-3" /> Website unverified
                        </span>
                      )}
                    </div>
                  </TableCell>

                  <TableCell>
                    {s.location ? (
                      <div className="flex items-center gap-1.5 text-slate-600">
                        <MapPin className="w-3.5 h-3.5 text-slate-400 shrink-0" />
                        {s.location}
                      </div>
                    ) : (
                      <span className="text-slate-400">—</span>
                    )}
                  </TableCell>

                  <TableCell>
                    <div className="flex flex-wrap gap-1.5">
                      {s.certifications
                        ? s.certifications.split(",").map((c, i) =>
                            c.trim() ? (
                              <Badge
                                variant="secondary"
                                key={i}
                                className="bg-slate-100 hover:bg-slate-200 text-slate-700 font-medium border-slate-200/60"
                              >
                                {c.trim()}
                              </Badge>
                            ) : null
                          )
                        : <span className="text-slate-400 text-sm">None listed</span>}
                    </div>
                  </TableCell>

                  <TableCell className="text-right font-mono text-sm text-slate-700">
                    {s.moq ? s.moq.toLocaleString() : <span className="text-slate-400">—</span>}
                  </TableCell>

                  <TableCell>
                    {s.score != null ? (
                      <div className="flex items-center gap-2.5">
                        <Progress value={scorePercent} className="w-20 h-2 bg-slate-100" />
                        <span className="text-xs font-bold text-slate-700 tabular-nums">{s.score}/{MAX_SCORE}</span>
                      </div>
                    ) : (
                      <span className="text-slate-400">—</span>
                    )}
                  </TableCell>

                  <TableCell className="text-right">
                    <Button
                      variant="outline"
                      size="sm"
                      className="text-xs h-8 border-slate-200 hover:border-primary/30 hover:bg-primary/5 hover:text-primary"
                      onClick={() => { setRfqSupplier(s); setCopied(false); }}
                      data-testid={`button-rfq-${s.id}`}
                    >
                      <FileText className="w-3.5 h-3.5 mr-1.5" />
                      RFQ Draft
                    </Button>
                  </TableCell>
                </TableRow>
              );
            })}
          </TableBody>
        </Table>
      </div>

      <Dialog open={!!rfqSupplier} onOpenChange={(open) => { if (!open) setRfqSupplier(null); }}>
        <DialogContent className="max-w-2xl max-h-[85vh] flex flex-col">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2 text-slate-900">
              <FileText className="w-5 h-5 text-primary" />
              RFQ Draft — {rfqSupplier?.name}
            </DialogTitle>
            <DialogDescription>
              Review and edit this template before sending. Fill in your company details where indicated.
            </DialogDescription>
          </DialogHeader>

          <div className="flex-1 overflow-auto mt-2">
            <pre className="text-xs text-slate-700 bg-slate-50 border border-slate-200 rounded-lg p-4 font-mono whitespace-pre leading-relaxed overflow-x-auto">
              {rfqText}
            </pre>
          </div>

          <div className="flex items-center gap-3 pt-4 border-t border-slate-100">
            <Button
              onClick={handleDownload}
              className="flex-1"
              data-testid="button-rfq-download"
            >
              <Download className="w-4 h-4 mr-2" />
              Download .txt
            </Button>
            <Button
              variant="outline"
              onClick={handleCopy}
              className="flex-1"
              data-testid="button-rfq-copy"
            >
              {copied ? (
                <><CheckCheck className="w-4 h-4 mr-2 text-green-500" /> Copied!</>
              ) : (
                <><Copy className="w-4 h-4 mr-2" /> Copy to Clipboard</>
              )}
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
}
